import Poem from "./Poem";
import styles from "./Poem.module.css";

const Poetry = () => {
  var iDo = [
    "​In seven days God made the Earth",
    "From darkness he brought light",
    "Till man and woman made he them",
    "Two beacons shining bright",
    "So many years of history",
    "Have passed from then to now",
    "Till here we stand for all to see",
    "Our oaths we both avow",
    "A precious moment just for us",
    "That seems to pause all time",
    "Before our friends, family, and God",
    "For you I wrote this rhyme",
    "I stand before you here and now",
    "Just me, and you, and Him",
    "Trying so hard to put to words",
    "With tears held on the brim",
    "What can I say that would suffice",
    "Could words ever convey",
    "The way I feel here next to you",
    "Our fates entwined today",
    "I'll do my best through tremored speech",
    "Describe what's deep within",
    "Profess to you all that I feel",
    "My vows will now begin",
    "I promise here to take your hand",
    "For you to be my wife",
    "To have and hold from this day on",
    "For my entire life",
    "For better, worse, richer, poorer",
    "Sickness and in health",
    "I promise I'll be at your side",
    "Our marriage is our wealth",
    "From this day forward evermore",
    "For death can never part",
    "I give my hand to you today",
    "With my entire heart",
    "I promise that I'll care for you",
    "In each and every way",
    "I promise saying I love you",
    "At least once every day",
    "I promise that I'll keep your trust",
    "I'll be honest and true",
    "I promise that I'll keep these vows",
    "I pledge here now to you",
    "I take thee Rachel as my wife",
    "A final phrase for you",
    "I seal all that I've said within",
    "I love you and I do",
  ];
  var theSoldier = [
    "A soldier stood before the gates",
    "Awaiting word from God",
    "Pondering his life events",
    "He knew had been so flawed",
    "Judgment now upon his soul",
    "He stood straight, proud, and true",
    "His name called out from heaven’s throne",
    "He left the winding queue",
    "Standing there before the Lord",
    "He waited patiently",
    "Knowing what was sure to come",
    "His sins for all to see",
    "Soldier what have you to say",
    "About your life on Earth",
    "Concerning all that you have done",
    "From death back to your birth",
    "Flipping through the Book of Life",
    "Recanting every choice",
    "The soldier paused to clear his throat",
    "Then said with humbled voice",
    "My God I’m not the best of men",
    "My life was full of sin",
    "One hand full of blood and guilt",
    "The other rum and gin",
    "I rarely ever went to church",
    "I hardly called your name",
    "And looking back upon my life",
    "My heart is full of shame",
    "Lord I don’t deserve this place",
    "It’s for a selfless heart",
    "It’s for the saints that loved you so",
    "Who played their Earthly part",
    "Upon recanting these short words",
    "The soldier bowed his head",
    "Unworthy to behold his lord",
    "His spirit full of dread",
    "Silence filled the holy place",
    "All eyes had turned to him",
    "Awaiting what the Lord would say",
    "His judgment looking grim",
    "Soldier you of anyone",
    "His verdict had begun",
    "Deserve to walk right through these gates",
    "When all is said and done",
    "You sacrificed so very much",
    "You fought your demons well",
    "My son your heart is full of love",
    "​You’ve done your time in hell",
  ];

  return (
    <div className={styles.poemRootDiv}>
      <Poem title="I Do" poem={iDo} />
      <Poem title="The Soldier" poem={theSoldier} />
    </div>
  );
};

export default Poetry;
